paths:
  - 'astro'
  - 'src'
fileTypes:
  - 'md'
  - 'mdx'
  - 'js'
  - 'ts'
#links:
#  - old: 'https://github.com/vixshan/mina'
#    new: 'https://github.com/vixshan/amina'
githubUrls:
  - all: 'true'
ignore:
  - 'https://github.com/Discordjs/discordjs'
  - 'https://github.com/saiteja-madha'